spring:
  application:
   name: mimigate

  cloud:
    gateway:

      routes:
        - id: mimi-rental
          uri: lb://mimi-rental
          predicates:
            - Path=/rental/**
        - id: mimi-users
          uri: lb://mimi-users
          predicates:
            - Path=/users/**
        - id: mimi-equipment
          uri: lb://mimi-equipment
          predicates:
            - Path=/equipment/**
      default-filters:
       - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: 'http://127.0.0.1:5675'
            allow-credentials: true
            allowedHeaders: '*'
            allowedMethods:
              - PUT
              - GET
              - POST
              - DELETE
              - OPTIONS

server:
  port: 5676

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:5677/eureka
#  instance:
#    lease-renewal-interval-in-seconds: 2

